
CREATE DATABASE studentDB

USE studentDB
ALTER DATABASE STUDENTDB MODIFY NAME = TeacherDB


DROP DATABASE bit23c
DROP DATABASE ParlourDb


CREATE DATABASE SCHOOLDB
 ALTER DATABASE SCHOOLDB MODIFY NAME  = CollegeDB

 DROP DATABASE 